'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Account
    Public Property Accounts_ID As Integer
    Public Property Accounts_Name As String

    Public Overridable Property Chart_Of_Accounts_Type As ICollection(Of Chart_Of_Accounts_Type) = New HashSet(Of Chart_Of_Accounts_Type)

End Class
