'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Auto_Number
    Public Property Auto_Number_id As Integer
    Public Property Sch_Shop_Invoice_Number As Nullable(Of Integer)
    Public Property Auto_Acc_No As Nullable(Of Integer)

End Class
