'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Chart_Of_Accounts_Type
    Public Property Chart_Of_Accounts_Type_ID As Integer
    Public Property Accounts_ID As Nullable(Of Integer)
    Public Property Chart_Of_Accounts_Type_Name As String

    Public Overridable Property Chart_Of_Accounts As ICollection(Of Chart_Of_Accounts) = New HashSet(Of Chart_Of_Accounts)
    Public Overridable Property Account As Account

End Class
