'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Chart_Of_Accounts
    Public Property Chart_Of_Accounts_ID As Integer
    Public Property Chart_Of_Accounts_Type_ID As Nullable(Of Integer)
    Public Property Chart_Of_Accounts_Code As String
    Public Property Chart_Of_Accounts_Description As String
    Public Property Chart_Of_Accounts_Beginning_Balances As Nullable(Of Double)
    Public Property Chart_Of_Accounts_Status As Nullable(Of Boolean)
    Public Property Chart_Of_Accounts_oName As String
    Public Property Chart_Of_Accounts_oFather As String
    Public Property Chart_Of_Accounts_oMobile As String

    Public Overridable Property Chart_Of_Accounts_Type As Chart_Of_Accounts_Type
    Public Overridable Property Chart_Of_Accounts_Detail As ICollection(Of Chart_Of_Accounts_Detail) = New HashSet(Of Chart_Of_Accounts_Detail)
    Public Overridable Property Sch_Accounts_Default As ICollection(Of Sch_Accounts_Default) = New HashSet(Of Sch_Accounts_Default)
    Public Overridable Property Sch_Accounts_Default1 As ICollection(Of Sch_Accounts_Default) = New HashSet(Of Sch_Accounts_Default)

End Class
