'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Chart_Of_Accounts_Detail
    Public Property Chart_Of_Accounts_Detail_ID As Integer
    Public Property Chart_Of_Accounts_ID As Nullable(Of Integer)
    Public Property Sch_Accounts_ID As Nullable(Of Integer)
    Public Property Chart_Of_Accounts_Detail_Account_Trans_No As String
    Public Property Chart_Of_Accounts_Detail_Account_Type As String
    Public Property Chart_Of_Accounts_Detail_Account_Ledger As String
    Public Property Chart_Of_Accounts_Detail_Account_Date As Nullable(Of Date)
    Public Property Chart_Of_Accounts_Detail_Account_Debit As Nullable(Of Decimal)
    Public Property Chart_Of_Accounts_Detail_Account_Credit As Nullable(Of Decimal)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Sch_Accounts As Sch_Accounts

End Class
