'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DbBilalAccountingsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DbBilalAccountingsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Chart_Of_Accounts() As DbSet(Of Chart_Of_Accounts)
    Public Overridable Property Chart_Of_Accounts_Detail() As DbSet(Of Chart_Of_Accounts_Detail)
    Public Overridable Property Chart_Of_Accounts_Type() As DbSet(Of Chart_Of_Accounts_Type)
    Public Overridable Property Sch_Accounts() As DbSet(Of Sch_Accounts)
    Public Overridable Property Sch_Accounts_Default() As DbSet(Of Sch_Accounts_Default)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Accounts() As DbSet(Of Account)
    Public Overridable Property Auto_Number() As DbSet(Of Auto_Number)

End Class
