'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sch_Accounts_Default
    Public Property Sch_Accounts_Default_ID As Integer
    Public Property Sch_Debit_Accounts_ID As Integer
    Public Property Sch_Credit_Accounts_ID As Nullable(Of Integer)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts1 As Chart_Of_Accounts
    Public Overridable Property Sch_Accounts As ICollection(Of Sch_Accounts) = New HashSet(Of Sch_Accounts)

End Class
